name: Build
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install dependencies
        run: sudo apt update --quiet=2 && sudo apt install flatpak flatpak-builder

      - name: Configure flathub remote
        run: flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build and install
        run: flatpak-builder --user --assumeyes --default-branch=nightly --force-clean --install-deps-from=flathub --install octave org.octave.Octave.yaml

      - name: Test running octave --version
        run: flatpak run --branch=nightly org.octave.Octave --version

      - name: Test running octave --eval ver
        run: flatpak run --branch=nightly org.octave.Octave --eval ver

      - name: Dump octave build configuration
        run: flatpak run --branch=nightly org.octave.Octave --eval "disp (__octave_config_info__)"
