name: Nightly build
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Cache flatpak build state directory
        uses: actions/cache@v2
        env:
          cache-name: cache-flatpak-state
        with:
          path: |
            .flatpak-builder
            !.flatpak-builder/build
            !.flatpak-builder/cache/refs/heads/*/build-octave
            !.flatpak-builder/ccache
            !.flatpak-builder/rofiles
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('org.octave.Octave.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: sudo apt install flatpak flatpak-builder

      - name: Configure flathub remote
        run: flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Delete any cached octave build results
        run: rm -rf .flatpak-builder/cache/refs/heads/*/build-octave

      - name: Build
        run: flatpak-builder --user --install-deps-from=flathub --assumeyes --default-branch=nightly octave org.octave.Octave.yaml

      - name: Export build to repository
        run: flatpak build-export --gpg-sign=${{ steps.gpg.outputs.keyid }} repo octave nightly

      - name: Update repository metadata
        run: flatpak build-update-repo --gpg-sign=${{ steps.gpg.outputs.keyid }} --default-branch=nightly repo

      - name: Publish repository to S3 bucket
        run: aws s3 sync repo s3://${{ secrets.AWS_S3_BUCKET }}/repo --acl public-read --delete
