name: Nightly build
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Nightly build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Cache flatpak build state directory
        uses: actions/cache@v2
        env:
          cache-name: cache-flatpak-builder
        with:
          path: |
            .flatpak-builder
            !.flatpak-builder/build
            !.flatpak-builder/ccache
            !.flatpak-builder/rofiles
          key: ${{ runner.os }}-nightly-${{ env.cache-name }}-${{ hashFiles('*.json', '*.patch', '*.yaml', 'shared-modules/**/*.json') }}
          restore-keys: |
            ${{ runner.os }}-nightly-${{ env.cache-name }}-
            ${{ runner.os }}-nightly-
            ${{ runner.os }}-

      - name: Install dependencies
        run: sudo apt install flatpak flatpak-builder

      - name: Configure flathub remote
        run: flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Delete unwanted leftover build stages from flatpak cache before building
        run: |
          ostree refs --repo=.flatpak-builder/cache --delete app runtime
          ostree refs --repo=.flatpak-builder/cache --delete x86_64-org.octave.Octave.yaml/build-octave
          ostree refs --repo=.flatpak-builder/cache --delete x86_64-org.octave.Octave.yaml/cleanup
          ostree refs --repo=.flatpak-builder/cache --delete x86_64-org.octave.Octave.yaml/finish
          ostree prune --repo=.flatpak-builder/cache --refs-only

      - name: Build and install
        run: flatpak-builder --user --assumeyes --default-branch=nightly --force-clean --install-deps-from=flathub --install octave org.octave.Octave.yaml

      - name: Test running octave --version
        run: flatpak run --branch=nightly org.octave.Octave --version

      - name: Test running octave --eval ver
        run: flatpak run --branch=nightly org.octave.Octave --eval ver

      - name: Dump octave build configuration
        run: flatpak run --branch=nightly org.octave.Octave --eval "disp (__octave_config_info__)"

      - name: Build and export
        run: flatpak-builder --user --assumeyes --default-branch=nightly --force-clean --install-deps-from=flathub --bundle-sources --gpg-sign=${{ steps.gpg.outputs.keyid }} --repo=repo octave org.octave.Octave.yaml

      - name: Update repository metadata
        run: flatpak build-update-repo --gpg-sign=${{ steps.gpg.outputs.keyid }} --default-branch=nightly repo

      - name: Publish repository to S3 bucket
        run: aws s3 sync repo s3://${{ secrets.AWS_S3_BUCKET }}/repo --acl public-read --delete

      - name: Delete unwanted final build stages from flatpak cache before saving
        run: |
          ostree refs --repo=.flatpak-builder/cache --delete app runtime
          ostree refs --repo=.flatpak-builder/cache --delete x86_64-org.octave.Octave.yaml/build-octave
          ostree refs --repo=.flatpak-builder/cache --delete x86_64-org.octave.Octave.yaml/cleanup
          ostree refs --repo=.flatpak-builder/cache --delete x86_64-org.octave.Octave.yaml/finish
          ostree prune --repo=.flatpak-builder/cache --refs-only
