name: Nightly build
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Cache flatpak build state directory
        uses: actions/cache@v2
        with:
          path: |
            .flatpak-builder
            !.flatpak-builder/build
            !.flatpak-builder/cache/refs/heads/*/build-octave
            !.flatpak-builder/rofiles

      - name: Install dependencies
        run: sudo apt install flatpak flatpak-builder

      - name: Configure flathub remote
        run: flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build
        run: flatpak-builder --user --install-deps-from=flathub --assumeyes octave org.octave.Octave.yaml

      - name: Create a repository
        run: |
          flatpak build-export --gpg-sign=${{ steps.gpg.outputs.keyid }} repo octave nightly
          flatpak build-update-repo --gpg-sign=${{ steps.gpg.outputs.keyid }} --default-branch=nightly repo
